### ISSUE TITLE
bevy 0.13 support is not on crates.io

### ISSUE THREAD

**Issue by Phil-hacker** [Adamkob12/bevy_meshem#12]
the pull request for bevy 0.13 support was already merged but no crates.io version got pushed

**Comment by Adamkob12** [comment]
Thanks for the heads up. I'll get to it soon.

I'll add that for now, you can specify rust dependencies directly from Git: 
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

**Comment by Adamkob12** [comment]
Should be up now!
